#!/bin/bash
#SCRIPT=`realpath $0`
#SCRIPTPATH=`dirname $SCRIPT`
SCRIPTPATH=`dirname $( realpath $0 )`
echo $SCRIPTPATH

echo "----------------------------------------"
echo "PanDelos-frags"
echo "University of Verona, Italy"
echo "Bonnici et al."
echo "----------------------------------------"


#CHECK THAT EVERY REQUIREMENT IS SATISFIED
#TODO
chmod +x $SCRIPTPATH/scripts/*.sh
#PATH=$PATH:${$SCRIPTPATH/scripts/}


if [ $# -ne 2 ]
  then
    echo "Usage: pandelos-frags ilist output_directory"
    exit 1
fi

ifile="$1"
odir="$2"

echo 'Selected input file: ${ifile}'
echo 'Selected output file ${odir}'

mkdir -p $odir
rm $odir/*
mkdir $odir/complete


while read -r line; do
    echo "$line"
    gtype=`echo -n $line | cut -d"," -f 2 |  tr -d '\r'`
    gfile=`realpath $( echo $line | cut -d"," -f 1 )`
    gname=`basename $gfile`
    echo "$gfile" 
    if [ "$gtype" = "complete" ]; then
        echo "COMPLETE"
        cat $gfile >> $odir/ALL_complete_genomes_genes.fna
        bash $SCRIPTPATH/scripts/complete_genome_genes_extraction.sh $gfile $odir/complete/$gname
        cat $odir/complete/$gname/gene_sequences.fna >> $odir/ALL_genes.fna
        cat $odir/complete/$gname/gene_sequences.fna >> $odir/genes_from_complete.fna
    else
        echo "FRAGMENTED"
        cat $gfile >> $odir/ALL_fragmented_genomes_genes.fna
        $SCRIPTPATH/scripts/reconstruct_genes.sh $gfile $odir/fragmented/$gname $gtype
        cat $odir/fragmented/$gname/results/gene_sequences.fna >> $odir/ALL_genes.fna
        cat $odir/fragmented/$gname/results/gene_sequences.fna >> $odir/genes_from_fragmented.fna
    fi
    echo "----------------------------------------"
done < "$ifile"

mkdir -p $odir
bash $SCRIPTPATH/PanDelosFork/pandelos.sh $odir/ALL_genes.fna $odir

python3 $SCRIPTPATH/scripts/get_fragment_coordinates.py $odir
bash $SCRIPTPATH/scripts/get_fragment_coordinates.sh $odir

echo "Done!"
